### ISSUE TITLE
DocumentHandler.saveAndPreviewBase64File does not work

### ISSUE THREAD

**Issue by TejendraGarge** [PolarCape/polarcape-cordova-plugin-document-handler#10]
I tried using the method DocumentHandler.saveAndPreviewBase64File(), it does not work.

it gives error "ReferenceError: Promise is not defined"

Can some one look into it!

**Comment by dorritydj** [comment]
Copying from [here](https://github.com/ti8m/DocumentHandler/issues/21) so this team is aware.

I actually came across this issue and worked to find the root cause. Android 7 no longer accepts the ```file://``` schema as the "data" for Intents, and now requires ```content://``` instead. The code needs to be updated to use ```FileProvider``` instead, specifically, [this line](https://github.com/PolarCape/polarcape-cordova-plugin-document-handler/blob/f047763b4d6efce70a6b47aed04418e6e5ff32a4/src/android/DocumentHandler.java#L183). In the meantime, a quick fix is to set the ```android:minSdkVersion="23"``` since this fails past 24. If someone on the plugin team could update with when this can be fixed, that would be great. 

http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed?noredirect=1&lq=1

**Comment by TejendraGarge** [comment]
Thanks Daniel.
Can I get some notification once plugin is updated?

Thanks & Regards
Tejendra Garge.
Digitization Team | TCS BPS | Tata Consultancy Services. | Website: http://www.tcs.com<http://www.tcs.com/>
Landline:- +91 22 677 84803 | Mobile: +91 9819288775 | Mailto: Tejendra.Garge@tcs.com<mailto:Tejendra.Garge@tcs.com>
……………………………………………………………………………….....................................................................
Experience certainty.
 IT Services…  Business Solutions…  Consulting…
……………………………………………………………………………….....................................................................

**Comment by TejendraGarge** [comment]
Even if it works, we cannot set the `android:minSdkVersion="23"` as some of the users are having Lollipop and KitKat in their device, so we need to cover those flavours as well.
Can you update the plugin to accomodate all the Android flavours right from Kitkat to latest Nougat.

I tried using `saveAndPreviewBase64File()` on KitKat (4.4.2), it does not work - gives error "**Promise is not defined**" .

**Comment by vkajtazov** [comment]
This issue is covered by #9

**Comment by TejendraGarge** [comment]
Dear vkajtazov.
Method `saveAndPreviewBase64File()` is not working for **KitKat** (4.4.2).

it gives error "_ReferenceError: Promise is not defined_"

Can some one look into it!
